// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteASPNET.Database;

namespace TesteASPNET.Migrations
{
    [DbContext(typeof(Conexao))]
    partial class ConexaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteASPNET.Models.Cliente", b =>
                {
                    b.Property<int>("CLI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CLI_ATIVO")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CLI_DATANASCIMENTO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CLI_NOME")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CLI_ID");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
